### ISSUE TITLE
getMousePos is not defined 

### ISSUE THREAD

**Issue by imSaharukh** [abtahi-tajwar/CGCodeGenerator#1]
getMousePos is not defined
    at (app.js:191)

![image](https://user-images.githubusercontent.com/25554766/119638559-9ad49080-be38-11eb-88df-b7e4901f8a2b.png)

![image](https://user-images.githubusercontent.com/25554766/119638602-a32ccb80-be38-11eb-8251-c429e337ed71.png)

**Comment by abtahi-tajwar** [comment]
There was a problem while uploading file so all the file wasn't uploaded correctly. It will work fine now!
